using UnityEngine;

namespace SignMasterVR.Lessons
{
    /// <summary>
    /// Defines a single sign the learner must reproduce (a letter, number, or word).
    /// Create instances via: Assets > Create > SignMasterVR > Gesture Data
    /// One asset per sign, stored under Assets/Data/Gestures/.
    /// The 26 letter assets + Level 1 are auto-generated by
    /// Tools > SignMasterVR > 1 Generate Alphabet Level (A-Z).
    /// </summary>
    [CreateAssetMenu(fileName = "Gesture_", menuName = "SignMasterVR/Gesture Data", order = 2)]
    public class GestureData : ScriptableObject
    {
        [Header("Identity")]
        [Tooltip("Internal id used by the ML classifier output, e.g. \"HELLO\", \"A\", \"1\". Must match the label the gesture recognition model returns.")]
        public string gestureId;

        [Tooltip("What the learner sees on screen, e.g. \"Letter A\", \"Hello\".")]
        public string displayName;

        [Header("Tutor")]
        [Tooltip("Name of the Animator trigger the TutorController plays to demonstrate this sign. Today every letter shares the generic \"Active\" placeholder trigger — give each its own real trigger once real per-sign animations exist, no other code needs to change.")]
        public string tutorAnimationTrigger = "Active";

        [Header("Reference material shown to the learner (Phase 11 / Step 30)")]
        [Tooltip("Flat reference image shown in the Correct Gesture panel. Use this first; swap for a 3D ghost-hand overlay later. Left empty for now — no reference photos exist yet.")]
        public Sprite referenceImage;

        [Header("Evaluation")]
        [Tooltip("Minimum confidence (0-1) the ML classifier must report for this to count as correct.")]
        [Range(0f, 1f)]
        public float requiredConfidence = 0.75f;

        [Header("Feedback")]
        [Tooltip("Text shown on success, e.g. \"Excellent!\"")]
        public string successMessage = "Excellent!";

        [Tooltip("Key looked up in AudioManager on success. Leave as-is until real recordings exist — AudioManager silently skips missing keys.")]
        public string successAudioKey = "Correct";

        [Tooltip("Key looked up in AudioManager on failure.")]
        public string tryAgainAudioKey = "TryAgain";
    }
}
