using UnityEngine;

namespace SignMasterVR.Lessons
{
    /// <summary>
    /// One learning level (Letters, Numbers, Basic Words, ...).
    /// Create via: Assets > Create > SignMasterVR > Level Data
    /// Store under Assets/Data/Levels/. Level 1 (Letters, all 26) is
    /// auto-generated by Tools > SignMasterVR > 1 Generate Alphabet Level (A-Z).
    /// </summary>
    [CreateAssetMenu(fileName = "Level_", menuName = "SignMasterVR/Level Data", order = 1)]
    public class LevelData : ScriptableObject
    {
        [Header("Identity")]
        public int levelNumber;
        public string levelName;
        [TextArea]
        public string description;

        [Header("Content")]
        [Tooltip("The gestures the learner must complete, in order, to finish this level.")]
        public GestureData[] gestures;

        [Header("Unlocking")]
        [Tooltip("Level that must be completed before this one unlocks. Leave empty for Level 1.")]
        public LevelData requiredPreviousLevel;
    }
}
