import socket
import json

class FeedbackNetworkSender:
    def __init__(self, target_ip="127.0.0.1", target_port=5005):
        """
        Initializes the network socket to communicate with the Unity VR headset.
        target_ip: IP address of the Meta Quest 3 or local machine running Unity.
        target_port: UDP port Group 4 is listening on.
        """
        self.target_ip = target_ip
        self.target_port = target_port
        self.sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)

    def send_feedback(self, payload_dict_or_json):
        """
        Encodes and transmits the JSON payload across the local network.
        """
        if isinstance(payload_dict_or_json, dict):
            message = json.dumps(payload_dict_or_json)
        else:
            message = str(payload_dict_or_json)

        data = message.encode("utf-8")
        self.sock.sendto(data, (self.target_ip, self.target_port))
        print(f"[Network] Sent to {self.target_ip}:{self.target_port} -> {message}")


# --- Test Execution ---
# Run this file directly to test local socket broadcasting
if __name__ == "__main__":
    sender = FeedbackNetworkSender(target_ip="127.0.0.1", target_port=5005)
    
    # Sample payload generated by your inference system
    sample_payload = {
        "predicted_sign": "HELLO",
        "confidence_score": 0.92,
        "status": "correct",
        "user_message": "Pass"
    }
    
    sender.send_feedback(sample_payload)